ignore:
  - "crates/**/tests/**/*"
  - "crates/**/examples/**/*"
  - "crates/**/benches/**/*"
  - "crates/**/build.rs"

  - "apps/**/tests/**/*"
  - "apps/**/examples/**/*"
  - "apps/**/benches/**/*"
  - "apps/**/build.rs"
